## Numpy 특징
- 고성능 과학 계산용 강력한 n차원 배열 객체
- 정교한 브로드캐스팅 기능 
- 반복문 없이 데이터 배열에 대한 처리를 지원하여 빠르고 편리

In [2]:
import numpy as np
np.__version__

'1.19.5'

### numpy 1차원

In [11]:
a1 = np.array([1,2,3,4,5])
print(a1)
print(type(a1))
print(a1.shape)
print(a1[0],a1[1],a1[2],a1[3],a1[4])
a1[0]=5
a1[1]=4
a1[2]=3
a1[3]=2
a1[4]=1
print(a1)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
1 2 3 4 5
[5 4 3 2 1]


### numpy 2차원

In [18]:
a2= np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a2)
print(a2.shape)
print(a2[0,0],a2[1,1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
1 5


### numpy 3차원

In [22]:
a3= np.array([[[1,2,3],[4,5,6],[7,8,9]],
            [[1,2,3],[4,5,6],[7,8,9]],
            [[1,2,3],[4,5,6],[7,8,9]]])
print(a3)
print(a3.shape)


[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
(3, 3, 3)


## 배열 생성 및 초기화

In [37]:
np.zeros(10) # 모든 요소를 0으로 초기화 

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [24]:
np.ones(10)# 모든 요소를 1로 초기화 

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [27]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [29]:
np.full((3,3),1.23)  # 해당 값으로 모두 넣어준다 

array([[1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23]])

In [34]:
for i in range(2,5):
    print(np.eye(i))#  np.eye 단위 행렬 

[[1. 0.]
 [0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [35]:
for i in range(2,5):
    print(np.tri(i))# np.tri 삼각 행렬 

[[1. 0.]
 [1. 1.]]
[[1. 0. 0.]
 [1. 1. 0.]
 [1. 1. 1.]]
[[1. 0. 0. 0.]
 [1. 1. 0. 0.]
 [1. 1. 1. 0.]
 [1. 1. 1. 1.]]


In [38]:
np.empty(10)  # 초기화 되지 않은 배열 생성 

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

- _like() 지정된 배열과 shape이 같은 행렬 생성 
-- np.zeros_like()
-- np.ones_like()
-- np.full_like()
-- np.empty_like()

In [43]:
np.zeros_like(a1)
print(a2)
np.ones_like(a2)
np.full_like(a3,10)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]]])

## 생성한 값으로 배열 생성

- arrange() 정수 범위로 배열 생성

In [45]:
np.arange(0,30,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

- linspace() 범위 내에서 균등 간격

In [47]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

- logspace() 범위 내에서 균등간격으로 로그 스케일로 배열생성

In [49]:
np.logspace(0.1,1,5)

array([ 1.25892541,  2.11348904,  3.54813389,  5.95662144, 10.        ])

## 랜덤값으로 배열 생성

- random.random() 랜덤한 수의 배열 생성

In [50]:
np.random.random((3,3))

array([[0.04045057, 0.38642446, 0.4387122 ],
       [0.63058189, 0.76736065, 0.70483705],
       [0.95612683, 0.65924778, 0.05192958]])

- random.randint() 랜덤한 수의 정수의 배열 생성

In [55]:
print(np.random.randint(0,10,4))
print(np.random.randint(0,10,(3,3)))

[6 8 2 1]
[[6 8 5]
 [6 4 1]
 [6 2 5]]


- random.normal() 정규 분포

In [56]:
np.random.normal(0,1,(3,3))

array([[-0.04646969,  0.21316861, -2.06866892],
       [-0.48381181, -0.20705712,  0.87438175],
       [-0.62082212, -0.92965184,  0.8868588 ]])

- random.rand() 균등 분포

In [57]:
np.random.rand(3,3)

array([[0.48179104, 0.5102546 , 0.63720904],
       [0.92991706, 0.86897537, 0.9723168 ],
       [0.50851646, 0.68101492, 0.46228123]])

- 표준 정규 분포

In [58]:
np.random.randn(3,3)

array([[ 0.53209444,  0.6399281 , -0.12385758],
       [-0.9104394 , -0.27315997, -1.27955595],
       [-0.06338012,  1.04766987,  0.4433625 ]])

## 표준 데이터 타입

In [61]:
np.zeros(20,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [62]:
np.zeros((3,3),dtype=bool)

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [63]:
np.ones((3,3),dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [65]:
np.full((3,3),1.0,dtype=float)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## 날짜/시간 배열 생성

In [72]:
date = np.array('2022-03-02',dtype=np.datetime64)
date


array('2022-03-02', dtype='datetime64[D]')

In [74]:
datetime =np.datetime64('2022-03-02 13:00')
datetime

numpy.datetime64('2022-03-02T13:00')

In [77]:
datetime = np.datetime64 ('2022-03-02 13:48:04.33','ns')
datetime

numpy.datetime64('2022-03-02T13:48:04.330000000')

## 배열 조회

In [80]:
def array_info(array):
    print(array)
    print("ndim:",array.ndim)
    print("shape",array.shape)
    print("dtype",array.dtype)
    print("size",array.size)
    print("itemsize",array.itemsize)
    print("nbytes",array.nbytes)
    print("strides",array.strides)

In [81]:
array_info(a1)

[5 4 3 2 1]
ndim: 1
shape (5,)
dtype int32
size 5
itemsize 4
nbytes 20
strides (4,)


In [82]:
array_info(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
ndim: 2
shape (3, 3)
dtype int32
size 9
itemsize 4
nbytes 36
strides (12, 4)


In [83]:
array_info(a3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
ndim: 3
shape (3, 3, 3)
dtype int32
size 27
itemsize 4
nbytes 108
strides (36, 12, 4)


## 인덱싱 

In [86]:
print(a1)
print(a1[2])
print(a1[-1])

[5 4 3 2 1]
3
1


In [88]:
print(a2)
print(a2[0,2])
print(a2[1,1])
print(a2[2,-1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
3
5
9


In [89]:
print(a3)
print(a3[0,0,0])
print(a3[1,1,1])
print(a3[2,2,2])

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
1
5
9


## 슬라이싱

In [93]:
print(a1)
print(a1[0:2])
print(a1[::-1])
print(a1[::2])

[5 4 3 2 1]
[5 4]
[1 2 3 4 5]
[5 3 1]


In [96]:
print(a2)
print(a2[1])
print(a2[1,:])
print(a2[:2,:2])
print(a2[::-1,::-1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[4 5 6]
[4 5 6]
[[1 2]
 [4 5]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]


## 불리언 인덱싱 

In [99]:
print(a1)
bi=[False,True,False,True,True]
print(a1[bi])

[5 4 3 2 1]
[4 2 1]


In [101]:
print(a2)
bi=np.random.randint(0,2,(3,3),dtype=bool)
print(bi)
print(a2[bi])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[False  True False]
 [False False False]
 [ True  True False]]
[2 7 8]


## 팬시 인덱싱

In [106]:
print(a1)
print(a1[0],a1[2])
idx = [0,2]
print(a1[idx])
idx = np.array([[0,1],
               [2,4]])
print(a1[idx])

[5 4 3 2 1]
5 3
[5 3]
[[5 4]
 [3 1]]


In [117]:
print(a2)
row = np.array([0,2])  # [0,1][2,2]
col = np.array([1,2])
print(a2[row,col])
print(a2[row,1])  # 2,8 
print(a2[1,col]) # 5, 6 
print(a2[row,:])
print(a2[:,col])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[2 9]
[2 8]
[5 6]
[[1 2 3]
 [7 8 9]]
[[2 3]
 [5 6]
 [8 9]]


## 배열 값 삽입/수정 /삭제/복사

### 배열 값 삽입
- insert  배열의 특정 위치에 값 삽입 
- 원본 배열 변경없이 새로운 배열 반환

In [123]:
print(a1)
b1 = np.insert(a1,0,10)
print(b1)
print(a1)


[5 4 3 2 1]
[10  5  4  3  2  1]
[5 4 3 2 1]


In [125]:
print(a2)
b2= np.insert(a2,1,10,axis=0)  # axis 0 은 row
print(b2)
c2 = np.insert(a2,1,10,axis=1) # axis 1 은 col 
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3]
 [10 10 10]
 [ 4  5  6]
 [ 7  8  9]]
[[ 1 10  2  3]
 [ 4 10  5  6]
 [ 7 10  8  9]]


### 배열 값 수정 
- 배열의 인덱싱을 접근하여 값 수정

In [132]:
print(a1)
a1[0]= 1
a1[1]= 2
a1[2]= 3
a1[3]=4
a1[4]=5
print(a1)

[9 9 9 9 9]
[1 2 3 4 5]


In [133]:
a1[::1]=9
print(a1)
a1

[9 9 9 9 9]


array([9, 9, 9, 9, 9])

In [139]:
print(a2)
a2[0,0]=0
a2[0]=3
a2[1:,2]=9
a2

[[3 3 3]
 [4 5 9]
 [7 8 9]]


array([[3, 3, 3],
       [4, 5, 9],
       [7, 8, 9]])

### 배열 값 삭제
- delete() 배열의 특정 위치에 값 삭제
- 원본 배열 변경없이 새로운 배열 반환
- 삭제할 방향을 axis로 지정

In [145]:
print(a1)
b1= np.delete(a1,1)
print(b1)

[9 9 9 9 9]
[9 9 9 9]


In [147]:
print(a2)
b2= np.delete(a2,1,axis=0)
print(b2)
c2= np.delete(a2,1,axis=1)
print(c2)

[[3 3 3]
 [4 5 9]
 [7 8 9]]
[[3 3 3]
 [7 8 9]]
[[3 3]
 [4 9]
 [7 9]]


### 배열 복사

- 복사의 경우 원본에 영향을 준다

In [154]:
print(a2)
print(a2[:2,:2])
a2_sub=a2[:2,:2]
print(a2_sub)
a2_sub[:,1]=0
print(a2_sub)
print(a2)

[[3 0 3]
 [4 0 9]
 [7 8 9]]
[[3 0]
 [4 0]]
[[3 0]
 [4 0]]
[[3 0]
 [4 0]]
[[3 0 3]
 [4 0 9]
 [7 8 9]]


- copy() 배열이나 하위 배열 내의 값을 명시적을 복사

In [162]:
print(a2)
a2_sub_copy=a2[:2,:2].copy()
print(a2_sub_copy)
a2_sub_copy[:,1]=1
print(a2_sub_copy)
print(a2)
# copy 를 이용할경우 원본에 영향 x 


[[3 0 3]
 [4 0 9]
 [7 8 9]]
[[3 0]
 [4 0]]
[[3 1]
 [4 1]]
[[3 0 3]
 [4 0 9]
 [7 8 9]]


## 배열 변환

### 배열 전치 및 축 변경

In [164]:
print(a2)
print(a2.T)

[[3 0 3]
 [4 0 9]
 [7 8 9]]
[[3 4 7]
 [0 0 8]
 [3 9 9]]


In [165]:
print(a3)
print(a3.T)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[[1 1 1]
  [4 4 4]
  [7 7 7]]

 [[2 2 2]
  [5 5 5]
  [8 8 8]]

 [[3 3 3]
  [6 6 6]
  [9 9 9]]]


In [166]:
print(a2)
print(a2.swapaxes(1,0))

[[3 0 3]
 [4 0 9]
 [7 8 9]]
[[3 4 7]
 [0 0 8]
 [3 9 9]]


In [167]:
print(a3)
print(a3.swapaxes(0,1))

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[[1 2 3]
  [1 2 3]
  [1 2 3]]

 [[4 5 6]
  [4 5 6]
  [4 5 6]]

 [[7 8 9]
  [7 8 9]
  [7 8 9]]]


### 배열 재구조화
- reshape() 배열의 형상을 변경

In [169]:
n1= np.arange(1,10)
print(n1)
print(n1.reshape(3,3))

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


- newaxis() 새로운 축 추가

In [172]:
print(n1)
print(n1[np.newaxis,:5])
print(n1[:5,np.newaxis])

[1 2 3 4 5 6 7 8 9]
[[1 2 3 4 5]]
[[1]
 [2]
 [3]
 [4]
 [5]]


### 배열 크기 변경

- 배열 모양만 변경

In [178]:
n2= np.random.randint(0,10,(2,5))
print(n2)
n2.resize((5,2))
print(n2)

[[5 7 4 5 8]
 [9 7 1 0 0]]
[[5 7]
 [4 5]
 [8 9]
 [7 1]
 [0 0]]


- 배열 크기 증가 
- 남은 공간은 0으로 채워짐

In [179]:
n2.resize((5,5))
print(n2)

[[5 7 4 5 8]
 [9 7 1 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


- 배열 크기 감소
- 포함되지 않은 값은 삭제됨 

In [180]:
n2.resize((3,3))
print(n2)

[[5 7 4]
 [5 8 9]
 [7 1 0]]


### 배열 추가 
- append() 배열의 끝에 값 추가

In [182]:
a2= np.arange(1,10).reshape(3,3)
print(a2)
b2 = np.arange(10,19).reshape(3,3)
print(b2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [183]:
c2 = np.append(a2,b2)
# append는 1차원 형태로 return 해준다 
print(c2)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


- axis 0으로 지정 


In [184]:
c2 = np.append(a2,b2,axis=0)
# append는 1차원 형태로 return 해준다 
print(c2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


- axis 1으로 지정

In [185]:
c2 = np.append(a2,b2,axis=1)
# append는 1차원 형태로 return 해준다 
print(c2)

[[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]


### 배열 연결

- concatenate() 튜플이나 배열의 리스트를 인수로 사용해 배열 연결

In [186]:
a1= np.array([1,3,5])
b1=np.array([2,4,7])
np.concatenate([a1,b1])

array([1, 3, 5, 2, 4, 7])

In [188]:
c1=np.array([7,8,9])
np.concatenate([a1,b1,c1])

array([1, 3, 5, 2, 4, 7, 7, 8, 9])

In [189]:
a2 = np.array([[1,3,5],
              [4,5,6]])
np.concatenate([a2,a2])

array([[1, 3, 5],
       [4, 5, 6],
       [1, 3, 5],
       [4, 5, 6]])

In [190]:
a2 = np.array([[1,3,5],
              [4,5,6]])
np.concatenate([a2,a2],axis=1)

array([[1, 3, 5, 1, 3, 5],
       [4, 5, 6, 4, 5, 6]])

- vstack() 수직 스택 1차원으로 연결

In [191]:
np.vstack([a2,a2])

array([[1, 3, 5],
       [4, 5, 6],
       [1, 3, 5],
       [4, 5, 6]])

- hstack() 수평 스택 1차원으로 연결

In [192]:
np.hstack([a2,a2])

array([[1, 3, 5, 1, 3, 5],
       [4, 5, 6, 4, 5, 6]])

- dstack() 깊이 스택 3차원으로 연결

In [193]:
np.dstack([a2,a2])

array([[[1, 1],
        [3, 3],
        [5, 5]],

       [[4, 4],
        [5, 5],
        [6, 6]]])

In [194]:
np.stack([a2,a2])

array([[[1, 3, 5],
        [4, 5, 6]],

       [[1, 3, 5],
        [4, 5, 6]]])

### 배열 분할

- split 배열 분할

In [197]:
a1= np.arange(0,10)
print(a1)
b1,c1=np.split(a1,[5])
print(b1,c1)
b1,c1,d1,e1,f1 = np.split(a1,[2,4,6,8])
print(b1,c1,d1,e1,f1)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4] [5 6 7 8 9]
[0 1] [2 3] [4 5] [6 7] [8 9]


- vsplit 수직분할 1차원으로 분할

In [199]:
a2 = np.arange(1,10).reshape(3,3)
print(a2)
b2,c2 = np.vsplit(a2,[2])
print(b2) 
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]]
[[7 8 9]]


- hsplit 수평 분할 2차원으로 분할

In [200]:
a2 = np.arange(1,10).reshape(3,3)
print(a2)
b2,c2 = np.hsplit(a2,[2])
print(b2) 
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]
 [7 8]]
[[3]
 [6]
 [9]]


- dsplit() 깊이 분할 ,3차원으로 분할

In [203]:
a3 = np.arange(1,28).reshape(3,3,3)
print(a3)
b3,c3 = np.dsplit(a3,[2])
print(b3) 
print(c3)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
[[[ 1  2]
  [ 4  5]
  [ 7  8]]

 [[10 11]
  [13 14]
  [16 17]]

 [[19 20]
  [22 23]
  [25 26]]]
[[[ 3]
  [ 6]
  [ 9]]

 [[12]
  [15]
  [18]]

 [[21]
  [24]
  [27]]]


## 배열 연산

### 브로드 캐스팅

In [209]:
a1= np.array([1,2,3])
print(a1)
print(a1+5)

a2 = np.arange(1,10).reshape(3,3)
print(a2)
print(a1+a2)

b2 = np.array([1,2,3]).reshape(3,1)
print(b1)
print(a1+b2)

[1 2 3]
[6 7 8]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]
[0 1]
[[2 3 4]
 [3 4 5]
 [4 5 6]]


### 산술연산

In [223]:
a1=np.arange(1,10)
print(a1)
print(a1+1)
print(np.add(a1,10))



[1 2 3 4 5 6 7 8 9]
[ 2  3  4  5  6  7  8  9 10]
[11 12 13 14 15 16 17 18 19]


In [221]:
print(a1-2)
print(np.subtract(a1,10))

[-1  0  1  2  3  4  5  6  7]
[-9 -8 -7 -6 -5 -4 -3 -2 -1]


In [222]:
print([-a1])
print(np.negative(a1))

[array([-1, -2, -3, -4, -5, -6, -7, -8, -9])]
[-1 -2 -3 -4 -5 -6 -7 -8 -9]


In [224]:
print(a1*2)
print(np.multiply(a1,2))

[ 2  4  6  8 10 12 14 16 18]
[ 2  4  6  8 10 12 14 16 18]


In [225]:
print(a1/2)
print(np.divide(a1,2))

[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]


In [226]:
print(a1//2)
print(np.floor_divide(a1,2))

[0 1 1 2 2 3 3 4 4]
[0 1 1 2 2 3 3 4 4]


In [228]:
print (a1 ** 2)
print(np.power(a1,2))

[ 1  4  9 16 25 36 49 64 81]
[ 1  4  9 16 25 36 49 64 81]


In [229]:
print(a1 % 2 )
print(np.mod(a1,2))

[1 0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0 1]


In [232]:
a1 = np.arange(1,10)
print(a1)
b1 = np.random.randint(1,10,size=9)
print(b1)
print(a1+b1)
print(a1-b1)
print(a1*b1)
print(a1/b1)
print(a1//b1)

[1 2 3 4 5 6 7 8 9]
[8 4 2 1 2 6 6 7 2]
[ 9  6  5  5  7 12 13 15 11]
[-7 -2  1  3  3  0  1  1  7]
[ 8  8  6  4 10 36 42 56 18]
[0.125      0.5        1.5        4.         2.5        1.
 1.16666667 1.14285714 4.5       ]
[0 0 1 4 2 1 1 1 4]


In [236]:
a2 = np.arange(1,10).reshape(3,3)
print(a2)
b2 = np.random.randint(1,10,size=(3,3))
print(b2)

print(a2+b2)
print(a2-b2)
print(a2*b2)
print(a2/b2)
print(a2//b2)
print(a2**b2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 9 9]
 [6 5 5]
 [6 9 5]]
[[ 2 11 12]
 [10 10 11]
 [13 17 14]]
[[ 0 -7 -6]
 [-2  0  1]
 [ 1 -1  4]]
[[ 1 18 27]
 [24 25 30]
 [42 72 45]]
[[1.         0.22222222 0.33333333]
 [0.66666667 1.         1.2       ]
 [1.16666667 0.88888889 1.8       ]]
[[1 0 0]
 [0 1 1]
 [1 0 1]]
[[        1       512     19683]
 [     4096      3125      7776]
 [   117649 134217728     59049]]


### 절대값 함수

In [242]:
a1= np.random.randint(-10,10,size=5)
print(a1)
print(np.abs(a1))


[ 8 -6 -5  6  3]
[8 6 5 6 3]


### 제곱 /제곱근 함수

In [244]:
print(a1)
print(np.square(a1))
print(np.sqrt(a1))

[ 8 -6 -5  6  3]
[64 36 25 36  9]
[2.82842712        nan        nan 2.44948974 1.73205081]


<ipython-input-244-4e034cb7ea92>:3: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(a1))


### 지수와 로그 함수

In [246]:
a1 = np.random.randint(1,10,size=5)
print(a1)
print(np.exp(a1))
print(np.exp2(a1))
print(np.power(a1,2))

[7 1 7 6 4]
[1096.63315843    2.71828183 1096.63315843  403.42879349   54.59815003]
[128.   2. 128.  64.  16.]
[49  1 49 36 16]


In [247]:
print(a1)
print(np.log(a1))
print(np.log2(a1))
print(np.log10(a1))

[7 1 7 6 4]
[1.94591015 0.         1.94591015 1.79175947 1.38629436]
[2.80735492 0.         2.80735492 2.5849625  2.        ]
[0.84509804 0.         0.84509804 0.77815125 0.60205999]


### 삼각 함수

In [250]:
t = np.linspace(0,np.pi,3)
print(t)
print(np.sin(t))
print(np.cos(t))
print(np.tan(t))

[0.         1.57079633 3.14159265]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [251]:
x=[-1,0,1]
print(x)
print(np.arcsin(x))
print(np.arccos(x))
print(np.arctan(x))

[-1, 0, 1]
[-1.57079633  0.          1.57079633]
[3.14159265 1.57079633 0.        ]
[-0.78539816  0.          0.78539816]


### 집계 함수

- sum() 합 계산

In [256]:
a2 =np.random.randint(1,10,size=(3,3))
print(a2)
print(a2.sum())
print(np.sum(a2))
print(a2.sum(axis=0))
print(np.sum(a2,axis=0))
print(a2.sum(axis=1))
print(np.sum(a2,axis=1))

[[1 6 6]
 [1 1 3]
 [7 5 5]]
35
35
[ 9 12 14]
[ 9 12 14]
[13  5 17]
[13  5 17]


- cumsum() 누적합 계산

In [257]:
print(a2)
print(np.cumsum(a2))
print(np.cumsum(a2,axis=0))
print(np.cumsum(a2,axis=1))

[[1 6 6]
 [1 1 3]
 [7 5 5]]
[ 1  7 13 14 15 18 25 30 35]
[[ 1  6  6]
 [ 2  7  9]
 [ 9 12 14]]
[[ 1  7 13]
 [ 1  2  5]
 [ 7 12 17]]


- diff() 차분 계산

In [258]:
print(a2)
print(np.diff(a2))
print(np.diff(a2,axis=0))
print(np.diff(a2,axis=1))

[[1 6 6]
 [1 1 3]
 [7 5 5]]
[[ 5  0]
 [ 0  2]
 [-2  0]]
[[ 0 -5 -3]
 [ 6  4  2]]
[[ 5  0]
 [ 0  2]
 [-2  0]]


- prod() 곱 계산

In [259]:
print(a2)
print(np.prod(a2))
print(np.prod(a2,axis=0))  # 세로
print(np.prod(a2,axis=1))  # 가로 

[[1 6 6]
 [1 1 3]
 [7 5 5]]
18900
[ 7 30 90]
[ 36   3 175]


- cumprod() 누적곱 계산

In [260]:
print(a2)
print(np.cumprod(a2))
print(np.cumprod(a2,axis=0))  # 세로
print(np.cumprod(a2,axis=1))  # 가로 

[[1 6 6]
 [1 1 3]
 [7 5 5]]
[    1     6    36    36    36   108   756  3780 18900]
[[ 1  6  6]
 [ 1  6 18]
 [ 7 30 90]]
[[  1   6  36]
 [  1   1   3]
 [  7  35 175]]


- dot()/ matmul(): 점곱/행렬곱 계산

In [262]:
print(a2)
b2=np.ones_like(a2)
print(b2)
print(np.dot(a2,b2))
print(np.matmul(a2,b2))

[[1 6 6]
 [1 1 3]
 [7 5 5]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[13 13 13]
 [ 5  5  5]
 [17 17 17]]
[[13 13 13]
 [ 5  5  5]
 [17 17 17]]


- tensordot () 텐서 곱 계산

In [264]:
print(a2)
print(b2)
print(np.tensordot(a2,b2))
print(np.tensordot(a2,b2,axes=0))
print(np.tensordot(a2,b2,axes=1))

[[1 6 6]
 [1 1 3]
 [7 5 5]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
35
[[[[1 1 1]
   [1 1 1]
   [1 1 1]]

  [[6 6 6]
   [6 6 6]
   [6 6 6]]

  [[6 6 6]
   [6 6 6]
   [6 6 6]]]


 [[[1 1 1]
   [1 1 1]
   [1 1 1]]

  [[1 1 1]
   [1 1 1]
   [1 1 1]]

  [[3 3 3]
   [3 3 3]
   [3 3 3]]]


 [[[7 7 7]
   [7 7 7]
   [7 7 7]]

  [[5 5 5]
   [5 5 5]
   [5 5 5]]

  [[5 5 5]
   [5 5 5]
   [5 5 5]]]]
[[13 13 13]
 [ 5  5  5]
 [17 17 17]]


- cross() :벡터 곱 

In [265]:
x=[1,2,3]
y=[4,5,6]
print(np.cross(x,y))

[-3  6 -3]


- inner()/outer()  내적 /외적

In [266]:
print(a2)
print(b2)
print(np.inner(a2,b2))
print(np.outer(a2,b2))

[[1 6 6]
 [1 1 3]
 [7 5 5]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[13 13 13]
 [ 5  5  5]
 [17 17 17]]
[[1 1 1 1 1 1 1 1 1]
 [6 6 6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6 6 6]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [3 3 3 3 3 3 3 3 3]
 [7 7 7 7 7 7 7 7 7]
 [5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5]]


- mean() :평균계산

In [267]:
print(a2)
print(np.mean(a2))
print(np.mean(a2,axis=0))
print(np.mean(a2,axis=1))

[[1 6 6]
 [1 1 3]
 [7 5 5]]
3.888888888888889
[3.         4.         4.66666667]
[4.33333333 1.66666667 5.66666667]


- std() 표준 편차 계산

In [268]:
print(a2)
print(np.std(a2))
print(np.std(a2,axis=0))
print(np.std(a2,axis=1))

[[1 6 6]
 [1 1 3]
 [7 5 5]]
2.282515398241571
[2.82842712 2.1602469  1.24721913]
[2.3570226  0.94280904 0.94280904]


- var() 분산 계산

In [269]:
print(a2)
print(np.var(a2))
print(np.var(a2,axis=0))
print(np.var(a2,axis=1))

[[1 6 6]
 [1 1 3]
 [7 5 5]]
5.209876543209877
[8.         4.66666667 1.55555556]
[5.55555556 0.88888889 0.88888889]


- min() 최소값

In [270]:
print(a2)
print(np.min(a2))
print(np.min(a2,axis=0))
print(np.min(a2,axis=1))

[[1 6 6]
 [1 1 3]
 [7 5 5]]
1
[1 1 3]
[1 1 5]


- max() 최대값

In [271]:
print(a2)
print(np.max(a2))
print(np.max(a2,axis=0))
print(np.max(a2,axis=1))

[[1 6 6]
 [1 1 3]
 [7 5 5]]
7
[7 6 6]
[6 3 7]


- argmin() 최소값 인덱스

In [272]:
print(a2)
print(np.argmin(a2))
print(np.argmin(a2,axis=0))
print(np.argmin(a2,axis=1))

[[1 6 6]
 [1 1 3]
 [7 5 5]]
0
[0 1 1]
[0 0 1]


- argmax() 최대값 인덱스

In [273]:
print(a2)
print(np.argmax(a2))
print(np.argmax(a2,axis=0))
print(np.argmax(a2,axis=1))

[[1 6 6]
 [1 1 3]
 [7 5 5]]
6
[2 0 0]
[1 2 0]


- median() 중앙값   평균이랑 다름 

In [274]:
print(a2)
print(np.median(a2))
print(np.median(a2,axis=0))
print(np.median(a2,axis=1))

[[1 6 6]
 [1 1 3]
 [7 5 5]]
5.0
[1. 5. 5.]
[6. 1. 5.]


- percentile() 백분위 수

In [277]:
a1 = np.array([0,1,2,3])
print(a1)
print(np.percentile(a1,[0,20,40,60,80,100],interpolation='linear'))
print(np.percentile(a1,[0,20,40,60,80,100],interpolation='higher'))
print(np.percentile(a1,[0,20,40,60,80,100],interpolation='lower'))
print(np.percentile(a1,[0,20,40,60,80,100],interpolation='nearest'))
print(np.percentile(a1,[0,20,40,60,80,100],interpolation='midpoint'))

[0 1 2 3]
[0.  0.6 1.2 1.8 2.4 3. ]
[0 1 2 2 3 3]
[0 0 1 1 2 3]
[0 1 1 2 2 3]
[0.  0.5 1.5 1.5 2.5 3. ]


- any()

In [281]:
a2 = np.array([[True,False,False],
             [False,False,True],
              [True,False,False]])
print(a2)
print(np.any(a2))
print(np.any(a2,axis=0))  # col
print(np.any(a2,axis=1))  # row 

[[ True False False]
 [False False  True]
 [ True False False]]
True
[ True False  True]
[ True  True  True]


- all()

In [284]:
a2 = np.array([[True,False,False],
             [True,True,True],
              [True,False,False]])
print(a2)
print(np.all(a2))
print(np.all(a2,axis=0))  # col
print(np.all(a2,axis=1))  # row 

[[ True False False]
 [ True  True  True]
 [ True False False]]
False
[ True False False]
[False  True False]


## 비교 연산

In [293]:
a1= np.arange(1,10)
print(a1)
print(a1==5)
print(a1!=5)
print(a1>5)
print(a1>=5)
print(a1<5)
print(a1<=5)


[1 2 3 4 5 6 7 8 9]
[False False False False  True False False False False]
[ True  True  True  True False  True  True  True  True]
[False False False False False  True  True  True  True]
[False False False False  True  True  True  True  True]
[ True  True  True  True False False False False False]
[ True  True  True  True  True False False False False]


In [299]:
a2= np.arange(1,10).reshape(3,3)
print(a2)
print(np.sum(a2))
print(np.count_nonzero(a2>5))
print(np.sum(a2>5))
print(a2==5)
print(a2!=5)
print(a2>5)
print(a2>=5)
print(a2<5)
print(a2<=5)
print(np.any(a2>5,axis=0))
print(np.any(a2>5,axis=1))
print(np.all(a2>5,axis=0))
print(np.all(a2>5,axis=0))




[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
4
4
[[False False False]
 [False  True False]
 [False False False]]
[[ True  True  True]
 [ True False  True]
 [ True  True  True]]
[[False False False]
 [False False  True]
 [ True  True  True]]
[[False False False]
 [False  True  True]
 [ True  True  True]]
[[ True  True  True]
 [ True False False]
 [False False False]]
[[ True  True  True]
 [ True  True False]
 [False False False]]
[ True  True  True]
[False  True  True]
[False False False]
[False False False]


In [301]:
a1 =np.array([1,2,3,4,5])
print(a1)
b1 = np.array([1,2,3,3,4])
print(b1)
print(np.isclose(a1,b1))

[1 2 3 4 5]
[1 2 3 3 4]
[ True  True  True False False]


In [307]:
a1=np.array([np.nan,2,np.inf,4,np.NINF])
print(a1)
print(np.isnan(a1))
print(np.isinf(a1))
print(np.isfinite(a1))

[ nan   2.  inf   4. -inf]
[ True False False False False]
[False False  True False  True]
[False  True False  True False]


### 불리언 연산자

In [317]:
a2= np.arange(1,10).reshape(3,3)
print(a2)
print((a2>5)&(a2<8))
print(a2[(a2>5)&(a2<8)])

print((a2>5)|(a2<8))
print(a2[(a2>5)|(a2<8)])

print((a2>5)^(a2<8))
print(a2[(a2>5)^(a2<8)])

print(~(a2>5) )
print(a2[~(a2>5)])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[False False False]
 [False False  True]
 [ True False False]]
[6 7]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[1 2 3 4 5 6 7 8 9]
[[ True  True  True]
 [ True  True False]
 [False  True  True]]
[1 2 3 4 5 8 9]
[[ True  True  True]
 [ True  True False]
 [False False False]]
[1 2 3 4 5]


### 배열 정렬

In [319]:
a1 = np.random.randint(1,10,size=10)
print(a1)
print(np.sort(a1)) #원본에 영향 x 
print(a1)  
print(np.argsort(a1)) # index 이용 
print(a1)

[7 7 1 4 8 1 6 6 6 6]
[1 1 4 6 6 6 6 7 7 8]
[7 7 1 4 8 1 6 6 6 6]
[2 5 3 6 7 8 9 0 1 4]
[7 7 1 4 8 1 6 6 6 6]


In [323]:
a2 = np.random.randint(1,10,(3,3))
print(a2)
print(np.sort(a2,axis=0))
print(np.sort(a2,axis=1))

[[1 9 4]
 [8 9 9]
 [9 7 6]]
[[1 7 4]
 [8 9 6]
 [9 9 9]]
[[1 4 9]
 [8 9 9]
 [6 7 9]]


### 부분정렬

- partition() 배열에서 k개의 작은 값을 반환

In [327]:
a1= np.random.randint(1,10,size=10)
print(a1)
print(np.partition(a1,3))

[9 1 3 7 8 4 4 9 9 9]
[3 1 4 4 7 8 9 9 9 9]


In [328]:
a2= np.random.randint(1,10,size=(5,5))
print(a2)
print(np.partition(a2,3))
print(np.partition(a2,3,axis=0))
print(np.partition(a2,3,axis=1))

[[2 6 8 4 3]
 [3 1 9 7 1]
 [1 3 2 8 5]
 [2 9 5 2 8]
 [8 9 2 4 9]]
[[2 3 4 6 8]
 [1 1 3 7 9]
 [1 2 3 5 8]
 [2 2 5 8 9]
 [4 2 8 9 9]]
[[2 1 2 2 1]
 [1 3 2 4 3]
 [2 6 5 4 5]
 [3 9 8 7 8]
 [8 9 9 8 9]]
[[2 3 4 6 8]
 [1 1 3 7 9]
 [1 2 3 5 8]
 [2 2 5 8 9]
 [4 2 8 9 9]]


## 배열 입출력

기본적으로 바이너리 형식으로 저장한다. 

In [331]:
a2= np.random.randint(1,10,size=(5,5))
print(a2)
np.save('a',a2)

[[2 1 1 1 8]
 [7 2 1 5 8]
 [9 3 2 8 7]
 [6 5 7 8 8]
 [1 7 8 3 9]]


In [333]:
ls

 C 드라이브의 볼륨에는 이름이 없습니다.
 볼륨 일련 번호: 365D-1CA4

 C:\Users\hp072\PythonDataWorkspace\Numpy 디렉터리

2022-03-02  오후 09:52    <DIR>          .
2022-03-02  오후 09:52    <DIR>          ..
2022-03-02  오후 02:19    <DIR>          .ipynb_checkpoints
2022-03-02  오후 09:52               228 a.npy
2022-03-02  오후 09:52            77,093 Numpy.ipynb
               2개 파일              77,321 바이트
               3개 디렉터리  73,342,365,696 바이트 남음


In [336]:
b2=np.random.randint(1,10,size=(5,5))
print(b2)
np.savez("ab",a2,b2)

[[1 2 5 3 4]
 [4 1 5 2 7]
 [4 5 7 5 7]
 [3 4 4 1 4]
 [3 5 5 2 4]]


In [337]:
ls

 C 드라이브의 볼륨에는 이름이 없습니다.
 볼륨 일련 번호: 365D-1CA4

 C:\Users\hp072\PythonDataWorkspace\Numpy 디렉터리

2022-03-02  오후 09:54    <DIR>          .
2022-03-02  오후 09:54    <DIR>          ..
2022-03-02  오후 02:19    <DIR>          .ipynb_checkpoints
2022-03-02  오후 09:52               228 a.npy
2022-03-02  오후 09:54               706 ab.npz
2022-03-02  오후 09:52            77,093 Numpy.ipynb
               3개 파일              78,027 바이트
               3개 디렉터리  73,345,904,640 바이트 남음


In [340]:
npy = np.load("a.npy")
print(npy)

[[2 1 1 1 8]
 [7 2 1 5 8]
 [9 3 2 8 7]
 [6 5 7 8 8]
 [1 7 8 3 9]]


In [343]:
npz = np.load("ab.npz")
print(npz.files)
print(npz["arr_0"])
print(npz["arr_1"])

['arr_0', 'arr_1']
[[2 1 1 1 8]
 [7 2 1 5 8]
 [9 3 2 8 7]
 [6 5 7 8 8]
 [1 7 8 3 9]]
[[1 2 5 3 4]
 [4 1 5 2 7]
 [4 5 7 5 7]
 [3 4 4 1 4]
 [3 5 5 2 4]]


In [345]:
print(a2)
np.savetxt("a.csv",a2,delimiter=',')

[[2 1 1 1 8]
 [7 2 1 5 8]
 [9 3 2 8 7]
 [6 5 7 8 8]
 [1 7 8 3 9]]


In [346]:
ls

 C 드라이브의 볼륨에는 이름이 없습니다.
 볼륨 일련 번호: 365D-1CA4

 C:\Users\hp072\PythonDataWorkspace\Numpy 디렉터리

2022-03-02  오후 09:57    <DIR>          .
2022-03-02  오후 09:57    <DIR>          ..
2022-03-02  오후 02:19    <DIR>          .ipynb_checkpoints
2022-03-02  오후 09:57               630 a.csv
2022-03-02  오후 09:52               228 a.npy
2022-03-02  오후 09:54               706 ab.npz
2022-03-02  오후 09:56            80,416 Numpy.ipynb
               4개 파일              81,980 바이트
               3개 디렉터리  73,341,648,896 바이트 남음


In [353]:
csv = np.loadtxt("a.csv",delimiter=',')
csv

array([[2., 1., 1., 1., 8.],
       [7., 2., 1., 5., 8.],
       [9., 3., 2., 8., 7.],
       [6., 5., 7., 8., 8.],
       [1., 7., 8., 3., 9.]])

In [354]:
print(b2)
np.savetxt("b.csv",b2,delimiter=',',fmt='%.2e',header='c1,c2,c3,c4,c5')

[[1 2 5 3 4]
 [4 1 5 2 7]
 [4 5 7 5 7]
 [3 4 4 1 4]
 [3 5 5 2 4]]


In [355]:
csv = np.loadtxt("b.csv",delimiter=',')
csv

array([[1., 2., 5., 3., 4.],
       [4., 1., 5., 2., 7.],
       [4., 5., 7., 5., 7.],
       [3., 4., 4., 1., 4.],
       [3., 5., 5., 2., 4.]])